import pandas as pd

variable_labels = [
    "Rule of Law Index Overall Score",
    "Factor 1: Constraints on Government Powers",    
    "1.1 Government powers are effectively limited by the legislature",    
    "1.2 Government powers are effectively limited by the judiciary",    
    "1.3 Government powers are effectively limited by independent auditing and review",    
    "1.4 Government officials are sanctioned for misconduct",    
    "1.5 Government powers are subject to non-governmental checks",    
    "1.6 Transition of power is subject to the law",    
    "Factor 2: Absence of Corruption",    
    "2.1 Government officials in the executive branch do not use public office for private gain",    
    "2.2 Government officials in the judicial branch do not use public office for private gain",    
    "2.3 Government officials in the police and the military do not use public office for private gain",    
    "2.4 Government officials in the legislative branch do not use public office for private gain",    
    "Factor 3: Open Government",    
    "3.1. Publicized laws and government data",    
    "3.2 Right to information",    
    "3.3 Civic participation",    
    "3.4 Complaint mechanisms",    
    "Factor 4: Fundamental Rights",    
    "4.1 Equal treatment and absence of discrimination",    
    "4.2 The right to life and security of the person is effectively guaranteed",    
    "4.3 Due process of the law and rights of the accused",    
    "4.4 Freedom of opinion and expression is effectively guaranteed",    
    "4.5 Freedom of belief and religion is effectively guaranteed",    
    "4.6 Freedom from arbitrary interference with privacy is effectively guaranteed",    
    "4.7 Freedom of assembly and association is effectively guaranteed",    
    "4.8 Fundamental labor rights are effectively guaranteed",   
    "Factor 5: Order and Security",    
    "5.1 Crime is effectively controlled",    
    "5.2 Civil conflict is effectively limited",    
    "5.3 People do not resort to violence to redress personal grievances",    
    "Factor 6: Regulatory Enforcement",    
    "6.1 Government regulations are effectively enforced",    
    "6.2 Government regulations are applied and enforced without improper influence",    
    "6.3 Administrative proceedings are conducted without unreasonable delay",    
    "6.4 Due process is respected in administrative proceedings",    
    "6.5 The government does not expropriate without lawful process and adequate compensation",    
    "Factor 7: Civil Justice",    
    "7.1 People can access and afford civil justice",    
    "7.2 Civil justice is free of discrimination",    
    "7.3 Civil justice is free of corruption",    
    "7.4 Civil justice is free of improper government influence",    
    "7.5 Civil justice is not subject to unreasonable delay",   
    "7.6. Civil justice is effectively enforced",    
    "7.7 Alternative dispute resolution mechanisms are accessible, impartial, and effective",    
    "Factor 8: Criminal Justice",    
    "8.1 Criminal investigation system is effective",    
    "8.2 Criminal adjudication system is timely and effective",    
    "8.3 Correctional system is effective in reducing criminal behavior",    
    "8.4 Criminal system is impartial",    
    "8.5 Criminal system is free of corruption",   
    "8.6 Criminal system is free of improper government influence",    
    "8.7 Due process of the law and rights of the accused"
]

bbox_coords = pd.DataFrame(
    [
        # UN regions
        ['Southern Europe', -10, 35, 30, 47],
        ['Southern Asia', 42, 5, 105, 40],
        ['Middle Africa', 5, -19.2, 35, 24.5],
        ['Western Asia', 25, 10, 65, 45],
        ['South America', -90, -60, -30, 15],
        ['Caribbean', -85, 8, -57, 28],
        ['Australia and New Zealand', 105, -50, 180, -5],
        ['Western Europe', -10, 35, 20, 60],
        ['Eastern Africa', 20, -27.5, 58, 22.8],
        ['Western Africa', -25, -1, 25, 28.5],
        ['Eastern Europe', 11, 40, 45, 65],
        ['Central America', -93, 5, -76, 20],
        ['South-Eastern Asia', 90, -11, 145, 29],
        ['Southern Africa', 10, -35, 55, -16],
        ['Northern America', -170, 13, -50, 88],
        ['Eastern Asia', 73, 20, 150, 55],
        ['Northern Europe', -25, 50, 36, 72],
        ['Northern Africa', -15, 9, 37, 40],
        ['Melanesia', 139, -20.5, 180, 0],
        ['Micronesia', 133, 3, 170, 11],
        ['Central Asia', 45, 35, 90, 56],
        ['Polynesia', -176, -22.5, -166, -12],

        # WJP regions
        ['East Asia and Pacific', 73, -48.7, 180, 54.8],
        ['Eastern Europe and Central Asia', 13, 35, 180, 88],
        ['EU, EFTA, and North America', -172, 24, 36, 88],
        ['Latin America and Caribbean', -119.5, -66, -29, 38.3],
        ['Middle East and North Africa', -19.5, 18, 64.3, 45], 
        ['South Asia', 57, 5, 100, 40], 
        ['Sub-Saharan Africa', -21, -36.9, 61.3, 38.3],

        # Additional WB regions
        ['Europe & Central Asia', -12, 33.5,88, 75],
        ['North America', -170, 24, -50, 88]

    ], 
    columns = ["region", "min_X", "min_Y", "max_X", "max_Y"]
)